name: Update Issue Status from Google Sheet

on:
  schedule:
    # Run every 10 minutes (less frequent than the main monitor)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-issue-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Update issue statuses
      env:
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python scripts/issue_status_updater.py 
